language: python
python:
 - "2.6"
 - "2.7"

install:
 - sudo apt-get install python-dev xvfb x11-utils 
 - sudo apt-get install scrot imagemagick python-gtk2 python-qt4
 - pip install -r requirements-test.txt
 - pip install .
 - pip install coveralls

script:  
 - xauth add :0 . `mcookie`
 - cd tests && nosetests -v --with-coverage --cover-package=pyscreenshot  .
  
after_success:
 - coveralls
